#pragma once
#include <iostream>
#include <stdlib.h>
#include <string.h>
#include <tchar.h>
#include <string>
#include <windows.h>
#include <windowsx.h>
#include <CommCtrl.h>
#include <filesystem>
#include <fstream> 
#include <atlstr.h>
#include "resource1.h"
#include <stdio.h>
#include <Aspose.Words.Cpp/LoadFormat.h>
#include <Aspose.Words.Cpp/Loading/DocumentDirection.h>
#include <Aspose.Words.Cpp/DocumentBase.h>
#include <Aspose.Words.Cpp/Document.h>
#include <Aspose.Words.Cpp/DocumentBuilder.h>
#include <Aspose.Words.Cpp/SaveFormat.h>
#include <shellapi.h>
#include <Aspose.PDF.Cpp/SaveFormat.h>
#include <Aspose.PDF.Cpp/Document.h>
#include <Aspose.PDF.Cpp/DocumentFactory.h>
