#pragma once
#include <iostream>
#include <stdlib.h>
#include <string.h>
#include <tchar.h>
#include <string>
#include <windows.h>
#include <windowsx.h>
#include <CommCtrl.h>
#include <filesystem>
#include <fstream> 
#include <atlstr.h>
#include "resource1.h"
#include <stdio.h>
#include <Aspose.Words.Cpp/DocumentBase.h>
#include <Aspose.Words.Cpp/Document.h>
#include <Aspose.Words.Cpp/DocumentBuilder.h>
